trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'ruby-azure-pipeline-demo:$(build.buildId)'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    pwd
    ls
    gem install bundler -v '1.17.1'
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rspec
  displayName: 'RSpec'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
